### PR TITLE
Add current owners

### PR DESCRIPTION
**Pull request by mfojtik**
FYI @johnkim76 @jmrodri

### CODE REVIEW

**Comment by mfojtik** [comment]
@bparees updating according to your suggestion.

@johnkim76 @jmrodri please lemme know if you need anything else.

**Comment by jmrodri** [comment]
@johnkim76 has left the team. Just keep me on it.

**Comment by bparees** [comment]
/hold

holding per https://github.com/openshift/template-service-broker/pull/6#issuecomment-514154335

**Comment by mfojtik** [comment]
@bparees @jmrodri updated

/hold cancel

**Pull request merged**
